<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Product;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class DatabaseSeeder extends Seeder
{
    public function run(): void
    {
        User::create([
            'name' => 'Nathalie Admin',
            'email' => 'admin@nathaliesbakeshop.test',
            'password' => 'password',
            'role' => 'admin',
        ]);

        // ── Categories ─────────────────────────────────────────────────────────
        $categories = [
            [
                'name'        => 'Empanadas',
                'slug'        => 'empanadas',
                'description' => 'Hand-folded and baked golden — each empanada is filled to order with Filipino-style savory stuffings.',
                'sort_order'  => 1,
            ],
            [
                'name'        => 'Ube & Buko Pies',
                'slug'        => 'ube-buko-pies',
                'description' => 'Whole pies and slices bursting with creamy custard, young coconut, and that unmistakable purple ube.',
                'sort_order'  => 2,
            ],
            [
                'name'        => 'Cakes',
                'slug'        => 'cakes',
                'description' => 'Celebration cakes, layered slices, and fully custom creations for every milestone.',
                'sort_order'  => 3,
            ],
            [
                'name'        => 'Kakanin & Rice Cakes',
                'slug'        => 'kakanin-pastries',
                'description' => 'Timeless Filipino rice cakes and native sweets made from glutinous rice, coconut, and cane sugar.',
                'sort_order'  => 4,
            ],
            [
                'name'        => 'Breads & Pastries',
                'slug'        => 'breads-pastries',
                'description' => 'Pillowy soft pan de sal, buttery rolls, and baked goods straight from the oven every morning.',
                'sort_order'  => 5,
            ],
            [
                'name'        => 'Cookies & Bars',
                'slug'        => 'cookies-bars',
                'description' => 'Irresistible bite-sized treats and chewy bars made with Filipino pantry staples.',
                'sort_order'  => 6,
            ],
        ];

        $categoryIds = [];
        foreach ($categories as $category) {
            $categoryIds[$category['slug']] = Category::create($category)->id;
        }

        // ── Products ────────────────────────────────────────────────────────────
        $products = [

            // ── Empanadas ──────────────────────────────────────────────────────
            [
                'category_id' => $categoryIds['empanadas'],
                'name'        => 'Classic Beef Empanada',
                'slug'        => 'classic-beef-empanada',
                'description' => 'Nathalie\'s most-requested hand pie. Seasoned ground beef slow-cooked with onion, potatoes, sweet raisins, and bell pepper — all tucked inside a rich, golden pastry shell. One bite and you\'ll understand why it disappears so fast at every gathering.',
                'price'       => 4.50,
                'variants'    => null,
                'image_url'   => '/images/seed/beef-empanada.jpg',
                'image_alt'   => 'Golden baked beef empanada on a wooden board',
                'is_featured' => true,
            ],
            [
                'category_id' => $categoryIds['empanadas'],
                'name'        => 'Chicken & Potato Empanada',
                'slug'        => 'chicken-potato-empanada',
                'description' => 'Shredded chicken breast sautéed with garlic, onion, carrots, and potatoes, finished with a light cream sauce and sealed in a buttery, flaky crust. A crowd favourite at family reunions and potlucks across the GTA.',
                'price'       => 4.25,
                'variants'    => null,
                'image_url'   => '/images/seed/chicken-empanada.jpg',
                'image_alt'   => 'Freshly baked chicken empanadas',
                'is_featured' => true,
            ],
            [
                'category_id' => $categoryIds['empanadas'],
                'name'        => 'Tuna & Corn Empanada',
                'slug'        => 'tuna-corn-empanada',
                'description' => 'A lighter, everyday option — flaked tuna blended with sweet kernel corn, onion, and a touch of grated cheese. Satisfying without being heavy, and perfect for packed lunches or afternoon merienda.',
                'price'       => 3.75,
                'variants'    => null,
                'image_url'   => '/images/seed/beef-empanada.jpg',
                'image_alt'   => 'Tuna and corn empanada on parchment paper',
                'is_featured' => false,
            ],
            [
                'category_id' => $categoryIds['empanadas'],
                'name'        => 'Longganisa Empanada',
                'slug'        => 'longganisa-empanada',
                'description' => 'Inspired by Vigan\'s famous breakfast — sweet and garlicky longganisa sausage crumbled with egg and a dash of vinegar, wrapped in a perfectly crimped crust. A bold, savory twist that\'s become a weekend favourite.',
                'price'       => 4.75,
                'variants'    => null,
                'image_url'   => '/images/seed/beef-empanada.jpg',
                'image_alt'   => 'Longganisa empanada with crimped edges',
                'is_featured' => true,
            ],
            [
                'category_id' => $categoryIds['empanadas'],
                'name'        => 'Veggie Empanada',
                'slug'        => 'veggie-empanada',
                'description' => 'A hearty, meat-free option filled with sautéed mushrooms, spinach, sweet potato, and a pinch of smoked paprika. Full of colour and flavour — nobody misses the meat.',
                'price'       => 3.50,
                'variants'    => null,
                'image_url'   => '/images/seed/chicken-empanada.jpg',
                'image_alt'   => 'Veggie empanada with golden crust',
                'is_featured' => false,
            ],
            [
                'category_id' => $categoryIds['empanadas'],
                'name'        => 'Empanada Party Tray',
                'slug'        => 'empanada-party-tray',
                'description' => 'Our most popular entertaining order — a tray of 24 assorted empanadas (beef, chicken, and tuna) ready for your party, birthday, or bayanihan gathering. Beautifully presented and arriving fresh from the oven.',
                'price'       => 98.00,
                'variants'    => ['Mixed 24-pc', 'All Beef 24-pc', 'All Chicken 24-pc'],
                'image_url'   => '/images/seed/beef-empanada.jpg',
                'image_alt'   => 'Large tray of assorted baked empanadas',
                'is_featured' => false,
            ],

            // ── Ube & Buko Pies ────────────────────────────────────────────────
            [
                'category_id' => $categoryIds['ube-buko-pies'],
                'name'        => 'Signature Ube Buko Pie',
                'slug'        => 'signature-ube-buko-pie',
                'description' => 'The pie that started it all. A silky, violet ube custard with real ube halaya blended into the filling, topped with tender strips of young coconut, all nestled in a buttery shortcrust pastry. Order early — it sells out every weekend.',
                'price'       => 28.00,
                'variants'    => ['Whole 9"', 'Half Pie', 'Slice'],
                'image_url'   => '/images/seed/ube-buko-pie.jpg',
                'image_alt'   => 'Purple ube buko pie with whipped topping',
                'is_featured' => true,
            ],
            [
                'category_id' => $categoryIds['ube-buko-pies'],
                'name'        => 'Classic Buko Pie',
                'slug'        => 'classic-buko-pie',
                'description' => 'Laguna-style and proud of it. Young coconut strips swim in a soft, milky custard with just the right sweetness — encased in a double-crust shell that\'s golden on the outside, melt-in-your-mouth within. A nostalgic favourite for anyone who grew up in the Philippines.',
                'price'       => 26.00,
                'variants'    => ['Whole 9"', 'Half Pie', 'Slice'],
                'image_url'   => '/images/seed/buko-pie.jpg',
                'image_alt'   => 'Classic coconut buko pie with lattice crust',
                'is_featured' => false,
            ],
            [
                'category_id' => $categoryIds['ube-buko-pies'],
                'name'        => 'Mango Buko Pie',
                'slug'        => 'mango-buko-pie',
                'description' => 'Philippine sunshine in every slice — sweet Carabao mango purée folded into a coconut custard filling with young buko strips. This tropical pie is a summertime staple and a guaranteed conversation starter at your next gathering.',
                'price'       => 29.00,
                'variants'    => ['Whole 9"', 'Slice'],
                'image_url'   => '/images/seed/mango-buko-pie.jpg',
                'image_alt'   => 'Mango buko pie with a golden crust',
                'is_featured' => false,
            ],
            [
                'category_id' => $categoryIds['ube-buko-pies'],
                'name'        => 'Ube Macapuno Pie',
                'slug'        => 'ube-macapuno-pie',
                'description' => 'Ube meets macapuno — an extra-indulgent pie where sweet sport coconut (macapuno) strips are swirled through a deep purple ube custard. Richer, creamier, and a touch more festive than the original.',
                'price'       => 32.00,
                'variants'    => ['Whole 9"', 'Slice'],
                'image_url'   => '/images/seed/ube-buko-pie.jpg',
                'image_alt'   => 'Ube macapuno pie with purple swirl topping',
                'is_featured' => true,
            ],
            [
                'category_id' => $categoryIds['ube-buko-pies'],
                'name'        => 'Pandan Buko Pie',
                'slug'        => 'pandan-buko-pie',
                'description' => 'Fragrant and subtly sweet — a light green pandan custard scented with fresh pandan leaf extract, layered over tender coconut strips in a flaky crust. Delicate, elegant, and wonderfully aromatic.',
                'price'       => 27.00,
                'variants'    => ['Whole 9"', 'Slice'],
                'image_url'   => '/images/seed/buko-pie.jpg',
                'image_alt'   => 'Pandan coconut pie with green-tinted custard',
                'is_featured' => false,
            ],
            [
                'category_id' => $categoryIds['ube-buko-pies'],
                'name'        => 'Ube Leche Flan Pie',
                'slug'        => 'ube-leche-flan-pie',
                'description' => 'Two of the Philippines\' most beloved desserts fused into one extraordinary pie. A burnt-caramel leche flan layer sits atop a smooth ube custard filling in a shortcrust shell — silky, rich, and absolutely unforgettable.',
                'price'       => 34.00,
                'variants'    => ['Whole 9"', 'Slice'],
                'image_url'   => '/images/seed/leche-flan.jpg',
                'image_alt'   => 'Ube leche flan pie with caramel glaze',
                'is_featured' => true,
            ],

            // ── Cakes ──────────────────────────────────────────────────────────
            [
                'category_id'    => $categoryIds['cakes'],
                'name'           => 'Custom Celebration Cake',
                'slug'           => 'custom-celebration-cake',
                'description'    => 'Whether it\'s a debut, a wedding, a baptism, or a "just because" moment — Nathalie will bring your vision to life. Share your theme, flavour preferences, and guest count, and we\'ll craft something truly one of a kind. Inquire at least 2 weeks in advance.',
                'price'          => 0,
                'variants'       => null,
                'image_url'      => '/images/seed/custom-cake.jpg',
                'image_alt'      => 'Elegant tiered celebration cake with floral decorations',
                'is_featured'    => true,
                'is_inquiry_only'=> true,
            ],
            [
                'category_id' => $categoryIds['cakes'],
                'name'        => 'Ube Chiffon Cake',
                'slug'        => 'ube-chiffon-cake',
                'description' => 'Light as a cloud, purple as royalty. This airy chiffon is steeped in ube halaya, frosted with freshly whipped cream, and finished with a generous heap of grated cheddar. The contrast of sweet cream and salty cheese is pure Filipino genius.',
                'price'       => 45.00,
                'variants'    => ['6 inch', '8 inch', '10 inch'],
                'image_url'   => '/images/seed/ube-chiffon.jpg',
                'image_alt'   => 'Purple layered ube chiffon cake with whipped cream',
                'is_featured' => true,
            ],
            [
                'category_id' => $categoryIds['cakes'],
                'name'        => 'Mango Float Cake',
                'slug'        => 'mango-float-cake',
                'description' => 'The beloved no-bake refrigerator cake — elevated. Layers of ripe mango slices, pillowy all-purpose cream, and honey grahams chilled overnight until they\'ve melded into something magical. Served cold, eaten fast.',
                'price'       => 38.00,
                'variants'    => ['6 inch', '8 inch'],
                'image_url'   => '/images/seed/custom-cake.jpg',
                'image_alt'   => 'Layered mango float cake with fresh mango on top',
                'is_featured' => true,
            ],
            [
                'category_id' => $categoryIds['cakes'],
                'name'        => 'Ube Tres Leches Cake',
                'slug'        => 'ube-tres-leches-cake',
                'description' => 'A luscious ube sponge soaked overnight in a blend of three milks — evaporated, condensed, and heavy cream — then blanketed in softly whipped topping and a drizzle of ube jam. Deeply moist, deeply comforting.',
                'price'       => 48.00,
                'variants'    => ['6 inch', '8 inch'],
                'image_url'   => '/images/seed/ube-chiffon.jpg',
                'image_alt'   => 'Ube tres leches cake sliced to reveal soaked sponge',
                'is_featured' => false,
            ],
            [
                'category_id' => $categoryIds['cakes'],
                'name'        => 'Chocolate Ube Swirl Cake',
                'slug'        => 'chocolate-ube-swirl-cake',
                'description' => 'For those who can\'t choose between chocolate and ube — this one settles the debate. Rich dark chocolate sponge marbled with ube batter, layered with chocolate ganache, and finished with a purple ube buttercream swirl. Dramatic and delicious.',
                'price'       => 52.00,
                'variants'    => ['6 inch', '8 inch', '10 inch'],
                'image_url'   => '/images/seed/ube-chiffon.jpg',
                'image_alt'   => 'Chocolate ube swirl cake with purple and brown layers',
                'is_featured' => false,
            ],
            [
                'category_id' => $categoryIds['cakes'],
                'name'        => 'Caramel Condensada Cake',
                'slug'        => 'caramel-condensada-cake',
                'description' => 'Inspired by the warm, amber sweetness of condensed milk caramel. A tender vanilla sponge soaked in caramel syrup, layered with soft caramel buttercream, and decorated with a glossy dulce de leche drip. Simple, satisfying, beloved.',
                'price'       => 42.00,
                'variants'    => ['6 inch', '8 inch'],
                'image_url'   => '/images/seed/custom-cake.jpg',
                'image_alt'   => 'Caramel condensada cake with golden drip decoration',
                'is_featured' => false,
            ],
            [
                'category_id' => $categoryIds['cakes'],
                'name'        => 'Sans Rival Cake',
                'slug'        => 'sans-rival-cake',
                'description' => 'A Filipino classic that lives up to its name — "without rival." Crisp cashew meringue layers sandwiched with silky French buttercream and toasted cashew bits throughout. Textural, nutty, buttery perfection.',
                'price'       => 60.00,
                'variants'    => ['6 inch', '8 inch'],
                'image_url'   => '/images/seed/custom-cake.jpg',
                'image_alt'   => 'Sans rival cake with cashew meringue layers',
                'is_featured' => true,
            ],

            // ── Kakanin & Rice Cakes ──────────────────────────────────────────
            [
                'category_id' => $categoryIds['kakanin-pastries'],
                'name'        => 'Bibingka',
                'slug'        => 'bibingka',
                'description' => 'Memories of Simbang Gabi wrapped in banana leaf. Our bibingka is made from rice flour and coconut milk, baked in earthen clay pots, and topped generously with salted duck egg, kesong puti, and a brush of real butter. Soft in the centre, lightly charred on the edges.',
                'price'       => 5.50,
                'variants'    => ['Regular', 'Large'],
                'image_url'   => '/images/seed/bibingka.jpg',
                'image_alt'   => 'Filipino bibingka rice cake on banana leaf with toppings',
                'is_featured' => true,
            ],
            [
                'category_id' => $categoryIds['kakanin-pastries'],
                'name'        => 'Puto',
                'slug'        => 'puto',
                'description' => 'Fluffy white steamed rice cakes — simple, pillowy, and endlessly snackable. Our puto is made from rice flour and coconut milk, steamed to a gentle bounce, and topped with a thin slice of salted cheese. Eaten as a snack, a side, or a midnight craving.',
                'price'       => 2.50,
                'variants'    => ['Plain', 'Cheese', 'Ube'],
                'image_url'   => '/images/seed/bibingka.jpg',
                'image_alt'   => 'Steamed puto rice cakes on a bamboo steamer',
                'is_featured' => false,
            ],
            [
                'category_id' => $categoryIds['kakanin-pastries'],
                'name'        => 'Kutsinta',
                'slug'        => 'kutsinta',
                'description' => 'Chewy, amber-coloured steamed rice cakes with a unique, slightly elastic texture that pairs perfectly with freshly grated coconut on top. Made with the traditional blend of rice flour, lye water, and brown sugar — there\'s nothing quite like it.',
                'price'       => 2.25,
                'variants'    => null,
                'image_url'   => '/images/seed/bibingka.jpg',
                'image_alt'   => 'Kutsinta rice cakes with grated coconut topping',
                'is_featured' => false,
            ],
            [
                'category_id' => $categoryIds['kakanin-pastries'],
                'name'        => 'Sapin-Sapin',
                'slug'        => 'sapin-sapin',
                'description' => 'Three distinct flavours in one beautiful layered kakanin — coconut at the base, ube in the middle, and jackfruit on top. Each layer is its own little world of flavour, made from glutinous rice flour and steamed patiently until perfectly set.',
                'price'       => 5.00,
                'variants'    => ['Per piece', 'Box of 6'],
                'image_url'   => '/images/seed/bibingka.jpg',
                'image_alt'   => 'Colourful sapin-sapin rice cake with purple and yellow layers',
                'is_featured' => true,
            ],
            [
                'category_id' => $categoryIds['kakanin-pastries'],
                'name'        => 'Maja Blanca',
                'slug'        => 'maja-blanca',
                'description' => 'Smooth, creamy coconut pudding set to just the right jelly-like firmness and studded with sweet kernel corn. Often called Filipino coconut pudding, maja blanca is a fiesta staple that brings everyone to the dessert table first.',
                'price'       => 4.50,
                'variants'    => ['Single serving', 'Family tray'],
                'image_url'   => '/images/seed/leche-flan.jpg',
                'image_alt'   => 'Creamy maja blanca coconut pudding on a serving plate',
                'is_featured' => false,
            ],
            [
                'category_id' => $categoryIds['kakanin-pastries'],
                'name'        => 'Leche Flan',
                'slug'        => 'leche-flan',
                'description' => 'Rich, trembling custard made with a dozen egg yolks, evaporated milk, and condensed milk — steamed low and slow until perfectly set beneath a glossy amber caramel layer. Individually portioned in traditional llanera moulds.',
                'price'       => 4.00,
                'variants'    => ['Single', 'Box of 4'],
                'image_url'   => '/images/seed/leche-flan.jpg',
                'image_alt'   => 'Caramel leche flan custard in a llanera mould',
                'is_featured' => true,
            ],
            [
                'category_id' => $categoryIds['kakanin-pastries'],
                'name'        => 'Palitaw',
                'slug'        => 'palitaw',
                'description' => 'Little flat rice dumplings that "float up" when they\'re done — hence the name. Coated in freshly grated coconut, rolled in white sugar, and finished with toasted sesame seeds. A simple, traditional merienda that transports you back to lola\'s kitchen.',
                'price'       => 2.75,
                'variants'    => null,
                'image_url'   => '/images/seed/bibingka.jpg',
                'image_alt'   => 'Palitaw rice dumplings with coconut and sesame coating',
                'is_featured' => false,
            ],
            [
                'category_id' => $categoryIds['kakanin-pastries'],
                'name'        => 'Biko',
                'slug'        => 'biko',
                'description' => 'Sticky glutinous rice slow-cooked in rich coconut milk and brown sugar, finished with a golden latik (coconut caramel) topping that crackles with each bite. Dense, sweet, and deeply satisfying — this is Filipino comfort food at its purest.',
                'price'       => 5.00,
                'variants'    => ['Single serving', 'Small tray', 'Full tray'],
                'image_url'   => '/images/seed/bibingka.jpg',
                'image_alt'   => 'Biko sticky rice cake with caramel coconut topping',
                'is_featured' => true,
            ],

            // ── Breads & Pastries ──────────────────────────────────────────────
            [
                'category_id' => $categoryIds['breads-pastries'],
                'name'        => 'Classic Pan de Sal',
                'slug'        => 'pan-de-sal',
                'description' => 'The bread of Philippine mornings. Soft, slightly sweet, and dusted with breadcrumbs — our pan de sal comes out of the oven in the early hours and sells quickly. Best eaten warm with butter, cheese, or a smear of peanut butter.',
                'price'       => 1.50,
                'variants'    => ['Single', 'Half dozen', 'Dozen'],
                'image_url'   => '/images/seed/ensaymada.jpg',
                'image_alt'   => 'Freshly baked pan de sal rolls on a tray',
                'is_featured' => true,
            ],
            [
                'category_id' => $categoryIds['breads-pastries'],
                'name'        => 'Ensaymada',
                'slug'        => 'ensaymada',
                'description' => 'Our beloved brioche-style roll is everything a good ensaymada should be — soft, pillowy, and richly buttered with a generous crown of sweet buttercream and a snowfall of finely grated sharp cheddar. A perfect afternoon companion to a cup of hot chocolate.',
                'price'       => 3.75,
                'variants'    => ['Classic', 'Ube Swirl', 'Double Cheese'],
                'image_url'   => '/images/seed/ensaymada.jpg',
                'image_alt'   => 'Soft ensaymada sweet roll topped with buttercream and cheese',
                'is_featured' => true,
            ],
            [
                'category_id' => $categoryIds['breads-pastries'],
                'name'        => 'Cheese Bread',
                'slug'        => 'cheese-bread',
                'description' => 'A pillowy, milk-enriched bun stuffed generously with a creamy, savoury cheese filling that pulls apart beautifully when torn open. Baked until the top is burnished gold. Kids go crazy for it; adults are quietly just as smitten.',
                'price'       => 2.75,
                'variants'    => null,
                'image_url'   => '/images/seed/ensaymada.jpg',
                'image_alt'   => 'Cheese-filled bread rolls freshly baked',
                'is_featured' => false,
            ],
            [
                'category_id' => $categoryIds['breads-pastries'],
                'name'        => 'Ube Pan de Sal',
                'slug'        => 'ube-pan-de-sal',
                'description' => 'A purple upgrade to the Filipino breakfast staple. Our ube pan de sal is kneaded with real ube halaya for a soft, fragrant crumb and a stunning violet hue. Best paired with cream cheese, kesong puti, or our homemade ube jam spread.',
                'price'       => 2.00,
                'variants'    => ['Single', 'Half dozen', 'Dozen'],
                'image_url'   => '/images/seed/ensaymada.jpg',
                'image_alt'   => 'Purple ube pan de sal rolls dusted with breadcrumbs',
                'is_featured' => true,
            ],
            [
                'category_id' => $categoryIds['breads-pastries'],
                'name'        => 'Monay',
                'slug'        => 'monay',
                'description' => 'Dense, chewy, and slightly sweet — the humble monay is the bread of the barrio and one of the oldest Filipino bakes. A satisfying, unpretentious snack that holds its own with a cup of strong black coffee.',
                'price'       => 1.75,
                'variants'    => null,
                'image_url'   => '/images/seed/ensaymada.jpg',
                'image_alt'   => 'Monay Filipino bread with a firm, domed crust',
                'is_featured' => false,
            ],
            [
                'category_id' => $categoryIds['breads-pastries'],
                'name'        => 'Pianono Roll',
                'slug'        => 'pianono-roll',
                'description' => 'A delicate Filipino swiss roll — featherlight sponge cake spread with sweet creamy filling, dusted with sugar, and rolled into a tight spiral. Slice it and you\'ll find a beautiful swirl that looks as good as it tastes.',
                'price'       => 3.25,
                'variants'    => ['Original', 'Ube', 'Mango'],
                'image_url'   => '/images/seed/ensaymada.jpg',
                'image_alt'   => 'Pianono roll cake with cream filling and sugar dusting',
                'is_featured' => false,
            ],
            [
                'category_id' => $categoryIds['breads-pastries'],
                'name'        => 'Putok Star Bread',
                'slug'        => 'putok-star-bread',
                'description' => 'Named for the way it "explodes" with character — a crusty, egg-washed bread with a crunchy exterior and a soft, slightly sweet interior. A bakeshop classic that\'s been loved for generations. Simple, sturdy, and genuinely good.',
                'price'       => 1.50,
                'variants'    => null,
                'image_url'   => '/images/seed/ensaymada.jpg',
                'image_alt'   => 'Putok star bread with a golden, crackling crust',
                'is_featured' => false,
            ],

            // ── Cookies & Bars ─────────────────────────────────────────────────
            [
                'category_id' => $categoryIds['cookies-bars'],
                'name'        => 'Ube Crinkle Cookies',
                'slug'        => 'ube-crinkle-cookies',
                'description' => 'Fudgy, chewy cookies rolled in powdered sugar that crackle dramatically when baked — revealing a vivid purple interior that makes them impossible to resist. Made with real ube halaya blended into the batter for depth of flavour that goes far beyond just colour.',
                'price'       => 3.00,
                'variants'    => ['Single', 'Box of 6', 'Box of 12'],
                'image_url'   => '/images/seed/bibingka.jpg',
                'image_alt'   => 'Purple ube crinkle cookies dusted with powdered sugar',
                'is_featured' => true,
            ],
            [
                'category_id' => $categoryIds['cookies-bars'],
                'name'        => 'Polvoron',
                'slug'        => 'polvoron',
                'description' => 'A delicate, melt-in-your-mouth shortbread made from toasted flour, powdered milk, sugar, and butter — pressed into pretty shapes and wrapped in colourful cellophane. A staple pasalubong gift and a beloved merienda across the Philippines.',
                'price'       => 2.00,
                'variants'    => ['Classic', 'Pinipig', 'Ube', 'Cashew'],
                'image_url'   => '/images/seed/bibingka.jpg',
                'image_alt'   => 'Polvoron shortbread rounds wrapped in cellophane',
                'is_featured' => true,
            ],
            [
                'category_id' => $categoryIds['cookies-bars'],
                'name'        => 'Butter Cashew Cookies',
                'slug'        => 'butter-cashew-cookies',
                'description' => 'Crisp-edged, golden butter cookies loaded with roughly chopped roasted cashews and a pinch of sea salt. Rich but not cloying, and completely addictive. A staple on Nathalie\'s holiday gift trays and Christmas cookie boxes.',
                'price'       => 2.75,
                'variants'    => ['Single', 'Box of 8'],
                'image_url'   => '/images/seed/bibingka.jpg',
                'image_alt'   => 'Butter cashew cookies on a rustic wooden board',
                'is_featured' => false,
            ],
            [
                'category_id' => $categoryIds['cookies-bars'],
                'name'        => 'Ube Halaya Bars',
                'slug'        => 'ube-halaya-bars',
                'description' => 'A buttery oat crumble base, a thick layer of smooth homemade ube halaya, and a golden crumble top. Cut into generous squares that pack a satisfying, jammy punch. Think of them as a Filipino take on the jam slice — and then forget the comparison entirely.',
                'price'       => 3.50,
                'variants'    => ['Single', 'Box of 6'],
                'image_url'   => '/images/seed/bibingka.jpg',
                'image_alt'   => 'Ube halaya bars with crumble topping cut into squares',
                'is_featured' => true,
            ],
            [
                'category_id' => $categoryIds['cookies-bars'],
                'name'        => 'Coconut Macaroons',
                'slug'        => 'coconut-macaroons',
                'description' => 'Filipino macaroons are a different delightful animal — these are dense, chewy mounds of desiccated coconut bound with condensed milk and baked until slightly crisp on the outside and pillowy within. Not to be confused with the French macaron. Better, really.',
                'price'       => 2.50,
                'variants'    => ['Single', 'Box of 6', 'Box of 12'],
                'image_url'   => '/images/seed/bibingka.jpg',
                'image_alt'   => 'Golden Filipino coconut macaroons in paper cups',
                'is_featured' => false,
            ],
            [
                'category_id' => $categoryIds['cookies-bars'],
                'name'        => 'Broas (Lady Fingers)',
                'slug'        => 'broas-lady-fingers',
                'description' => 'Light, airy, and delicately sweet — the classic Filipino broas are made from whipped eggs and flour, baked until they have the perfect amount of snap. Beloved as a standalone snack or layered into mango float, ref cake, and other icebox desserts.',
                'price'       => 4.50,
                'variants'    => ['Pack of 12', 'Pack of 24'],
                'image_url'   => '/images/seed/ensaymada.jpg',
                'image_alt'   => 'Filipino broas lady finger biscuits in a pack',
                'is_featured' => false,
            ],
        ];

        foreach ($products as $product) {
            $product['is_inquiry_only'] = $product['is_inquiry_only'] ?? false;
            $product['is_active']       = $product['is_active'] ?? true;
            $product['is_featured']     = $product['is_featured'] ?? false;
            Product::create($product);
        }
    }
}

